config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  devise_for :users, :path_prefix => 'dv'
  resources :users
  resources :houses, only: [:index, :show]
  resource :houses, only: [:search] do
    post 'search', to: 'home#search'
  end
  get 'republic_announce', to: 'users#republic_announce'
  resources :users do
    resources :houses do
      resources :tags, only: [:create, :index]
    end
  end
  root to: "home#index"
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to user_house_url(id: @house.id), notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to user_house_url(id: @house.id), notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to user_houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(
        :title,
        :description,
        :rooms,
        :vacancies,
        :rent,
        :active,
        :street,
        :number,
        :neighborhood,
        :city,
        :state
      )
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_for [current_user, @house] do |f| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class= 'tab-content'>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :title, "Título do Anúncio" %><br />
      <%= f.text_field :title %>
    </div>

    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :description, "Descrição" %><br />
      <%= f.text_field :description %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :rooms, "Número de Quartos" %><br />
      <%= f.text_field :rooms %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :vacancies, "Vagas Disponíveis" %><br />
      <%= f.text_field :vacancies %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :rent, "Mensalidade" %><br />
      <%= f.text_field :rent %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :active, "Anúncio Ativo?" %><br />
      <%= f.text_field :active %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :street, "Rua" %><br />
      <%= f.text_field :street %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :number, "Número" %><br />
      <%= f.text_field :number %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :neighborhood, "Bairro" %><br />
      <%= f.text_field :neighborhood %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :city, "Cidade" %><br />
      <%= f.text_field :city %>
    </div>
    <div class="field" style="padding: 2% 20% 23px 20%;">
      <%= f.label :state, "Estado" %><br />
      <%= f.text_field :state %>
    </div>


    <div class="actions" style="padding: 0 20% 23px 20%;">
      <%= f.submit "Anunciar", style: "background-color: #039be5; border-radius: 5px; width: 40%; color: white; height: 30px; margin-left: 10%;" %>
      <%= link_to "<button style='background-color: #ff1a1a; border: 2px solid #ff1a1a; border-radius: 5px; color: white; height: 30px; width: 40%'>Voltar</button>".html_safe, user_houses_path %>
    </div>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Ver', user_house_url(id: @house.id) %> |
<%= link_to 'Voltar', user_houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>
<% if request.original_url.include?('users') %>
  <h1> Seus Anúncios</h1>
<% else %>
  <h1>Repúblicas</h1>
<% end %>

<table class="text-center">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        <th>Título</th>
        <th>Vagas Disponíveis</th>
        <th>Aluguel</th>
        <th>Cidade</th>
    <% @houses.each do |house| %>
      <tr class="text-center">
        <td><%= link_to "#{house.title}", house_url(id: house.id) %></td>
        <td><%=house.vacancies %></td>
        <td><%=house.rent %></td>
        <td><%=house.city %></td>
        <% if request.original_url.include?("users/") && house.id == current_user.id%>
          <td><%= link_to 'Edit', edit_user_house_path(id: house.id) %></td>
          <td><%= link_to 'Destroy', user_house_url(id: house.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if request.original_url.include?('users') %>
  <%= link_to 'Anunciar Republica', new_user_house_path %>
<% end %>

app/views/houses/new.html.erb
<h1 style= "text-align: center;">Anunciar República</h1>

<%= render 'form', house: @house %>

<%= link_to 'Voltar', user_houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<% if request.original_url.include?('users') %>
  <%= link_to 'Editar', edit_user_house_path(@house) %> |
  <%= link_to 'Voltar', user_houses_path %>
<% else %>
  <%= link_to 'Voltar', houses_path %>
<% end %>