config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  devise_for :users, :path_prefix => 'dv'
  resources :users
  resources :houses, only: [:index, :show]
  resource :houses, only: [:search] do
    post 'search', to: 'home#search'
  end
  get 'republic_announce', to: 'users#republic_announce'
  resources :users do
    resources :houses do
      resources :tags, only: [:create, :index]
    end
  end
  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Republic</title>
    <%= csrf_meta_tags %>
    <!-- <p class="notice" style="text-align: center;"><%= notice %></p>
    <p class="alert" style="text-align: center;"><%= alert %></p> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyD8PCvzfWfLKkH8mWT7NgKsaCpWjb4dxK0"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

    <% if user_signed_in? %>
      <ul id="slide-out" class="side-nav">
        <li><div class="user-view">
          <div class="background black">
          </div>
          <% unless current_user.avatar_file_name.nil? %>
            <%= link_to image_tag(current_user.avatar.url(:medium), class: 'media-object'), current_user.avatar.url, target: '_blank' %>
          <% else %>
            <%= link_to image_tag('missing-image-avatar.png') %>
          <% end %>
          <h5> <%= link_to current_user.name, edit_user_path(current_user), style: 'text-decoration: none; color: white' %> </h5>
          <h6> <%= current_user.email %></h6>
          <br>
        </div></li>
        <div class="row">
          <div class="container">
            <li><h6>Idade: 20</li>
            <li><h6>Telefone: 27222222</li>
            <li><div class="divider"></div></li>
            <li><h6>Cidade: Campos dos Goytacazes</h6></li>
            <li><h6>Estado: RJ</h6></li>
            <%= link_to('Anuncie Uma Vaga', new_user_house_path(user_id: current_user.id), method: :get) %></br>
            <%= link_to('Seus Anúncios', user_houses_path(user_id: current_user.id), method: :get) %></br>
            <%= link_to('Sair', destroy_user_session_path, method: :delete) %>
          </div>
        </div>
      </ul>
    <% end %>

      <div class="navbar-fixed">
        <nav>
          <div class="nav-wrapper">
            <div class="container-fluid">
              <% if user_signed_in? %>
                <a class="brand-logo button-collapse-sidenav" data-activates="slide-out"><i class="material-icons">menu</i></a>
              <% end %>
              <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li></li>
                <li><a class="nav-link" href="#">Ajuda</a></li>
                <li><a class="nav-link" href="<%= new_user_session_path %>">Entrar</a></li>
                <li><a class="nav-link" href="<%= republic_announce_path %>">Anuncie uma vaga</a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
  </head>

  <body>
    <%= yield %>
  </body>
</html>